### ISSUE TITLE
Add meta tags and google tag manager

### ISSUE THREAD

**Issue by StMacLennan** [StMacLennan/road-to-code#4]
- [ ] add meta tag gem
- [ ] setup default meta tag data
- [ ] add google tag manager gem
- [ ] set up google tags
